# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.cache/wt} [current_project]
set_property parent.project_path {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/NATY/AppData/Roaming/Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {e:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/imports/new/DIVIZOR_DE_FRECVENTA.vhd}
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/imports/new/TX FSM MODULE.vhd}
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/imports/new/RX FSM MODULE.vhd}
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/imports/new/RX TX MODULE.vhd}
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/imports/new/FINITE STATE MACHINE MOUSE MODULE.vhd}
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/new/Mouse cursor draw.vhd}
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/new/VGA Synchronization Circuit.vhd}
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/new/RGB VGA Sync.vhd}
  {E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/new/Mouse to VGA.vhd}
}
read_ip -quiet {{E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{e:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/constrs_1/imports/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{E:/FACULTATE/AN 3/SEMESTRUL 1/SSC/PROIECT/PROIECT_SSC/PROIECT_SSC.srcs/constrs_1/imports/new/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mouse_to_vga -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mouse_to_vga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mouse_to_vga_utilization_synth.rpt -pb mouse_to_vga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
